### ISSUE TITLE
Images built with --build-tech-preview that depend on another TP image cannot be built

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#153]
Consider this image definition:

```yaml
schema_version: 1

version: 1.0
name: jboss-amqmaas-1/amqmaas10-routermetrics-openshift
description: "Metrics for AMQMaas"
from: jboss-amqmaas-1-tech-preview/amqmaas10-qpidproton-openshift:1.0
```

We have two use cases:

1. Build image locally / CI
2. Build image in OSBS

Both are actually facing the same issue. If we build the image without `--build-tech-preview` for loca/CI build we will not be able to find the `jboss-amqmaas-1-tech-preview/amqmaas10-qpidproton-openshift:1.0` image, because the base image is not built locally/on CI with the `--build-tech-preview` switch.

On the other hand we have OSBS. We will be fine as long as we will build the TP images there, only. When we switch to a GA release build - we will need to adjust it in the source. The whole point of `--build-tech-preview` switch was about not polluting the image definition with the TP content and decide at build time what image it is. Issue arise when we base on another TP image.

We need to find elegant solution for it.
