### ISSUE TITLE
Provide better doc on implicit names

### ISSUE THREAD

**Issue by dbecvarik** [cekit/cekit#154]
If we are using repositories defined as:

``` yaml
        git:
          ref: master
          url: https://github.com/jboss-openshift/cct_module.git
```
it cannot be overriden via:
``` yaml
        git:
         path: /home/user/.../cct_module
```

because it will generate different names 'cct_module.git' vs 'cct_module'  we should explain this explicitly in docs and also we should suggest to define repositories in images descriptor with name attribute present as follows:

``` yaml
        git:
          name: cct_module
          ref: master
          url: https://github.com/jboss-openshift/cct_module.git
```
