### ISSUE TITLE
support external artifacts via NVR/koji/OSBS

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#157]
(more detail to come) based on several internal discussions; rather than use the koji lookaside cache (populating "sources" file and uploading to it) support fetching artifacts from koji via NVR (this is an OSBS feature) i.e. generate fetch-artifacts-koji.yaml , this might aid reproducibility.

(this is kind of a placeholder enhancement request issue, need to flesh it out with info from the people who know more :))

**Comment by jonathanchristison** [comment]
One other cool side effect of using this pre-build hook as either a module or merging with the artifacts module would be the possibility of having just one place to keep track of the version of a particular artifact and auto copying - 


Some badly written pseudo code follows -

```
artifacts:
- nvr: com.sun.xml.bind.mvn-jaxb-parent-2.2.11.redhat_4-1
  archives:
    # pull a specific archive
    - filename: jaxb-core-2.2.11.redhat-4.jar 
      group_id: org.glassfish.jaxb
      image_target: /opt/foo/foo.jar
```
Where ``image_target`` is the location artifact should be copied to, this skips out the need for ``ln``/``mv`` steps in custom build scripts.


It might also be possible to exact relevant Envs and Labels from the artifacts? for example -
```
{% for label in labels %}
{% for artifact in artifacts %}
LABEL io.fabric8.s2i.version.{{artifact.name()}}="{{artifact.version()}}
```
