### ISSUE TITLE
Make possible to copy artifacts to defined location in images

### ISSUE THREAD

**Issue by rwngwn** [cekit/cekit#158]
@jonathanchristison mentioned in #157 
One other cool side effect of using this pre-build hook as either a module or merging with the artifacts module would be the possibility of having just one place to keep track of the version of a particular artifact and auto copying - 

Some badly written pseudo code follows -

```
artifacts:
- nvr: com.sun.xml.bind.mvn-jaxb-parent-2.2.11.redhat_4-1
  archives:
    # pull a specific archive
    - filename: jaxb-core-2.2.11.redhat-4.jar 
      group_id: org.glassfish.jaxb
      image_target: /opt/foo/foo.jar
```
Where ``image_target`` is the location artifact should be copied to, this skips out the need for ``ln``/``mv`` steps in custom build scripts.
