### ISSUE TITLE
Add 'package.remove' to yum/rpm uninstall packages that already exist

### ISSUE THREAD

**Issue by grdryn** [cekit/cekit#177]
I imagine this could already be done in a module, but it might be nice to have the `packages` section to make it cleaner / more explicit.

Use case for removing packages: If a base image contains devel or header packages that are built from an SRPM that is tied to a CVE, `oscap-docker image-cve` will say that the image contains the vulnerability. Since we build our artifacts outside of the image and then just add them through the `artifacts` section, we don't need those packages, and can reduce the number of image rebuilds we have to do to pick up package updates that we don't use.

Example:
```yaml
packages
    install:
        - bash
    remove:
        - kernel-devel
        - kernel-headers
```
