### ISSUE TITLE
Schema v2 tracker

### ISSUE THREAD

**Issue by dbecvarik** [cekit/cekit#206]
This issue is here for tracking schema changes.

# 1. repository for yum packages
``` yaml
packages:
      repositories:
           - jboss-os
```
will be changed to defining repositories as a full objects as follows
``` yaml
packages:
      repositories:
            - name: rhel-7-server-ose-3.7-rpms
```
where repository name must be a real name of puddle content set which will be created by ODCS.
