### ISSUE TITLE
Dependency ordering is broken

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#237]
Modules that may depend on other modules will fail to install properly if the depend on items installed by other modules.  This is illustrated by a simple example:

```yaml
---moduleA.yaml
modules:
  install:
  - name: moduleB
execute:
- script: configure.sh # cat /foo.txt

---moduleB.yaml
execute:
- script: configure.sh # echoe "fubar" >> /foo.txt

---image.yaml
modules:
  install:
  - name: moduleA
```

The above will fail because module A script is executed before module B.
