### ISSUE TITLE
package.repository.url.repository should use the repository url instead of a link to a file containing the repository definition

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#262]
I'm happy to be trying to misuse this, but it doesn't seem very useful to point to a url which contains a .repo file, when the critical part of the .repo file is the repository url.  Why not just generate the repo file using the url specified, e.g.

```yaml
packages:
  repositories:
  - name: rhos
    url: 
      repository: "http://download.redhat.com/released/RHEL-7/7.5/Server/x86_64/os/"
      gpg: "http://download.redhat.com/released/RHEL-7/7.5/Server/x86_64/os/RPM-GPG-KEY-redhat-release"
  - name: rhscl
    url: 
      repository: "http://download.redhat.com/released/RHSCL/3.1/RHEL-7/Server/x86_64/os/"
      gpg: "http://download.redhat.com/released/RHSCL/3.1/RHEL-7/Server/x86_64/os/RPM-GPG-KEY-redhat-release"
```
