### ISSUE TITLE
cannot override environment variable values in modules

### ISSUE THREAD

**Issue by rcernich** [cekit/cekit#283]
moduleA
```yaml
env:
- name: foo
  value: bar
```

moduleB
```yaml
env:
- name: foo
  value: baz
modules:
  install:
  - name: moduleA
```

image.yaml
```yaml
modules:
  install:
  - name: moduleB
```

Notice that image has foo=bar.

**Comment by dbecvarik** [comment]
IT seems something wrong is happening in merging. I'll probably take a deeper look at merging code as it was tweaked multiple times and its probably time to revisit it and see if it can be make less complex and less error prone.

**Comment by jmtd** [comment]
With the exact case above, using cekit built from develop as of around now, I get foo=baz in the generated Dockerfile. I.e. the parent module is not overridden by the child.

What behaviour do we want?

**Comment by dbecvarik** [comment]
parent values overrides child.. so if a module introduce any variable you can change it in image.yaml (image descriptor is parent of all modules)

**Comment by jmtd** [comment]
With 2.0.0rc4 I get foo=bar, with develop (`--version => 2.1.rc0`) I get foo=baz

**Comment by rcernich** [comment]
Here's a more specific example.  It's not a child module, but a subsequent module, so...

image.yaml
```yaml
modules:
  install:
  - name: moduleA
  - name: moduleB
```
Using the same module definitions listed above.

HTH
