### ISSUE TITLE
Remove documentation by default

### ISSUE THREAD

**Issue by ruromero** [cekit/cekit#321]
When installing packages, in order to reduce the size of the images, they could be installed with the `--setopt=tsflags=nodocs` by default.

Suggestion taken from [Container Best Practices](http://docs.projectatomic.io/container-best-practices/#_removing_documentation)

E.g.
```
packages:
  repositories:
    - name: base
      id: rhel-7-server-rpms
  install:
    - java-1.8.0-openjdk
```
Would lead to
```
RUN yum install -y --setopt=tsflags=nodocs java-1.8.0-openjdk \
    && yum clean all && rm -rf /var/cache/yum && \
    rpm -q  java-1.8.0-openjdk
```
