### ISSUE TITLE
image help pages: make it an image property instead of cekit config

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#377]
Two enhancements I think we should make to the image doc/help.md generation

 * whether or not to generate docs by default (when `--add-help` is not specified) should be configurable in the image source itself. So an image can set an expectation that it is generated, rather than being specific to the builder's environment. So extending the image schema
 * we should support a command-line substitution of the help template, in addition to config file based. This is so we could (more easily) generate say, some docs that can be more easily consumed by an upstream docs team, instead of the default template which is designed to end up being piped to `man(1)` and so lacks more useful mark up like tables

**Comment by goldmann** [comment]
The first thing I would like to do is to understand the documentation generation, afterwards I could probably give some input to these bullets. I think this should be done before 3.0.

**Comment by jmtd** [comment]
Feel free to ask any questions!

**Comment by goldmann** [comment]
@jmtd I'm starting work on this ticket.

I found that it would make indeed sense to move the switch to add or not the documentation to the image to the image descriptor itself.

For the other issue, I would move this to separate, because this would also mean investigation of the main Dockerfile template. I added a comment in #407.

**Comment by goldmann** [comment]
For the implementation of this ticket I propose extending image definition (only, so not available in module definition) with something like this:

```yaml
doc:
  image: true
  modules: true
  template: doc-template.jinja
```

Where:

* default template path is what is shipped with CEKit.
* default `image` is set to False
* default `modules` is set to False
* `modules` is currently a noop, see https://github.com/cekit/cekit/issues/268

**Comment by goldmann** [comment]
Hrm, it looks like the template path is already there (taken from definition):

```yaml
help:
  map:
    template: {type: text}
```

So we could extend it this way:

```yaml
help:
  map:
    template: {type: text}   # Path to template
    image: {type: bool}      # Should image help be generated
```
