### ISSUE TITLE
Remove support for old type repostitories

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#386]
Triggered by #385. The deprecation message is there for a while, we can safely remove support for it.

```
2019-02-14 09:50:20,632 cekit        WARNING  The way of defining repository 'jboss-os' is deprecated. Convert it to an URL based repository object. Consult Cekit docs, for more details.
```

Old repositories are defined like this:

```yaml
packages:
  repositories:
    - jboss-os
```
