### ISSUE TITLE
module choice issue (multiple providers) 

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#451]
With [this image source](https://github.com/jmtd/openjdk/tree/rhel8-2k19) (branch rhel8-2k19, commit 503685f9621f91183a1d9fcfcf65cbe8f5745b84) and [this module cloned locally](https://github.com/jmtd/cct_module/tree/rhel82k19) (branch rhel82k1 commit d5e432eeedc503ca2c68744d0167741b0bbd54a9), I get the following behaviour I try `cekit --overrides-file rhel8-jdk11-overrides.yaml generate` with cekit version 2.2.6.

the `rhel8-jdk11-overrides.yaml` specifically lists module name `jboss.container.maven.35.bash`  and version "3.5". That cct_module branch has two modules that provide  `jboss.container.maven.35.bash`, one version "3.5" and another version "3.5scl".

After running that generate command, we can see in `target/image/modules/jboss.container.maven.35.bash` the correct module (version 3.5).

However, `target/image.yaml` contains the contents of *both* modules, and the image won't build (because the other version of the module, the one we don't want, installs `rh-maven35` which does not exist in UBI8).

The image depends up on the module `jboss.container.maven.35.bash` indirectly by module dependencies, too, as follows:

image.yaml → jboss.container.java.s2i.bash → jboss.container.maven.s2i.bash → jboss.container.maven.default.bash → jboss.container.maven.35.bash

That last dependency link is a name-only link, it does not specify any version of the module.

**Comment by jmtd** [comment]
I have not yet reproduced this with develop branch due to #450 .

**Comment by goldmann** [comment]
I checked this with `develop` and here is the resulting `image.yaml`:

```yaml
artifacts: []
description: Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK 11
envs:
- name: PATH
  value: $PATH:"/usr/local/s2i"
- name: JBOSS_IMAGE_NAME
  value: openjdk/openjdk-11-rhel8
- name: JBOSS_IMAGE_VERSION
  value: '1.0'
from: ubi8:latest
labels:
- name: io.k8s.description
  value: Platform for building and running plain Java applications (fat-jar and flat
    classpath)
- name: io.k8s.display-name
  value: Java Applications
- name: io.openshift.tags
  value: builder,java
- name: com.redhat.component
  value: openjdk-11-rhel8-container
- name: usage
  value: https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html/red_hat_java_s2i_for_openshift/
- name: io.cekit.version
  value: 3.0.dev0
- name: description
  value: Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK 11
- name: summary
  value: Source To Image (S2I) image for Red Hat OpenShift providing OpenJDK 11
modules:
  install:
  - name: jboss.container.user
  - name: jboss.container.openjdk.jdk
    version: '11'
  - name: jboss.container.s2i.core.api
  - name: jboss.container.maven.s2i.api
  - name: jboss.container.s2i.core.bash
  - name: jboss.container.maven.api
  - name: jboss.container.java.jvm.api
  - name: jboss.container.proxy.api
  - name: jboss.container.java.proxy.bash
  - name: jboss.container.java.jvm.bash
  - name: jboss.container.maven.35.bash
    version: '3.5'
  - name: jboss.container.util.logging.bash
  - name: jboss.container.maven.default.bash
  - name: jboss.container.maven.s2i.bash
  - name: jboss.container.java.run.bash
  - name: jboss.container.hawkular.api
  - name: jboss.container.hawkular.bash
  - name: jboss.container.jolokia.api
  - name: jboss.container.jolokia.bash
  - name: jboss.container.prometheus.api
  - name: jboss.container.prometheus.bash
  - name: jboss.container.java.s2i.bash
  repositories:
  - name: cct_module
    path: /home/goldmann/git/redhat/cct_module
    target: cct_module
name: openjdk/openjdk-11-rhel8
osbs:
  configuration:
    container:
      compose:
        include_unpublished_pulp_repos: true
        pulp_repos: true
packages:
  content_sets:
    x86_64:
    - rhel-8-for-x86_64-baseos-rpms
    - rhel-8-for-x86_64-appstream-rpms
  manager: yum
  repositories: []
  repositories_injected: []
ports:
- name: 8080
  value: 8080
- name: 8443
  value: 8443
run:
  cmd:
  - /usr/local/s2i/run
  name: run
  user: 185
  workdir: /home/jboss
schema_version: 1
version: '1.0'
volumes: []
```

There is only a single `jboss.container.maven.35.bash` module requested with the `3.5` version, so I suppose this is what is expected.

I was able to build the image just fine with changes mentioned here: https://github.com/cekit/cekit/issues/450#issuecomment-475146507.

```
2019-03-21 11:15:02,196 cekit        INFO     Image built and available under following tags: openjdk/openjdk-11-rhel8:1.0, openjdk/openjdk-11-rhel8:latest
2019-03-21 11:15:02,196 cekit        INFO     Finished!
```
