### ISSUE TITLE
Environment variables defined in image descriptor are not available anymore while building the image

### ISSUE THREAD

**Issue by goldmann** [cekit/cekit#490]
**Describe the bug**
When we have image descriptor with an env variable;

```yaml
envs:
  - name: "SUBMARINE_HOME"
    value: "/home/submarine"
```
it is not available during installation of this module.

**To reproduce**
Steps to reproduce the behavior. Try to describe as detailed as possible what lead you to the issue.

**Expected behavior**
The `SUBMARINE_HOME` should be defined and available during module install.

**Logs**
None

**Environment information:**
3.0.0

**Additional context**
None
