### ISSUE TITLE
envs on cekit modules are not getting overridden as expected.

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#513]
**Describe the bug**
CEKit build with modules's environment variable that needs to be overridden are not working as expected. 
In our case, we have this environment variable: https://github.com/jboss-container-images/rhpam-7-image/blob/master/kieserver/modules/kieserver/module.yaml#L25
Which holds a jar name with a specific version.

Sometimes we need to update this value using overrides file so we can use a newer version of it without update the git hub.

But if we use a override with the content:

```yaml
envs:
    - name: "JBPM_WB_KIE_SERVER_BACKEND_JAR"
      value: "jbpm-wb-kie-server-backend-7.4.0.redhat-20190515.jar"
artifacts:
    - name: "KIE_SERVER_DISTRIBUTION_ZIP"
      target: "kie_server_distribution.zip"
      #     rhpam-7.4.0.PAM-redhat-20190515-kie-server-ee8.zip
      md5: "5d4069c134bac50163d675178dbc1e8e"
    - name: "BUSINESS_CENTRAL_DISTRIBUTION_ZIP"
      target: "business_central_distribution.zip"
      #     rhpam-7.4.0.PAM-redhat-20190515-business-central-eap7-deployable.zip
      md5: "47160c3a4a10a1601742362b1536de93"
```

The overrides, instead to happen in the rhpam-7-kieserver module is made on the image.yaml file: 

```
cat target/image.yaml | grep JBPM_WB_KIE_SERVER_BACKEND_JAR
- name: JBPM_WB_KIE_SERVER_BACKEND_JAR
```

And the result on the Dockerfile, will contain 2 envs with different values:

```
 cat target/image/Dockerfile | grep JBPM_WB_KIE_SERVER_BACKEND_JAR
    JBPM_WB_KIE_SERVER_BACKEND_JAR="jbpm-wb-kie-server-backend-7.4.0.redhat-20190512.jar" 
    JBPM_WB_KIE_SERVER_BACKEND_JAR="jbpm-wb-kie-server-backend-7.4.0.redhat-20190515.jar" 
```

**To reproduce**
Try to override some env value from a CEKit module.

**Expected behavior**
It should override the env value instead add a new one.

**Logs**
Paste any logs you have, use CEKit verbose output: `cekit -v`.

 - CEKit version: Result of `cekit --version`
3.0.1

**Additional context**

**Comment by goldmann** [comment]
Initially I wrote a comment, but I need to go back to code. I'll review it and provide better answer afterwards.

**Comment by goldmann** [comment]
OK, I'm now better suited to reply to this issue 😏

This is another result of the change to processing of modules that was introduced in 3.0. As you know we process modules serially and we install modules in order defined in the image definition. You used overrides mechanism, where the specified env variable was not defined in the image descriptor, so it was added. Image descriptor content is processed/installed at the end and this is where it was placed in Dockerfile, again. First was the module install, second is the image descriptor (overrides in your case).

After looking at the code I found that the only possible things that you can currently **override** in modules are:

1. Module version requirement for modules added in some module itself
2. Artifacts

No other things can be overridden currently.

I understand that this may not be what you expected and you feel that this is a bug. I'm not sure if I would describe it as a bug tbh. **What would be the expected way it should work?** Let's see what options we have:

1. **Process image descriptor at the beginning**
    In this case it will be overridden by the module either case. Additionally it will produce unexpected changes to the resulting image, because modules will now be processed after image descriptor. This is probably a no-go.
2. **Overrides process image descriptor, modules are not touched**
    This is, more or less current state with the difference that we're able to override artifacts and module versions as stated above.
3. **Override every module**
    For each processed module, override it with passed overrides. This opens additional questions.
    * What should happen in case where overrides has no impact? Should it be silently ignored?
    * How we should know where exactly apply the override (to which module)?
    * What if the overridden thing (env variable for example) will be used in multiple modules? Should we override every module?

I'm open for discussion. We need a clear way of describing how overrides work and what to expect. I also opened https://github.com/cekit/cekit/issues/514. I'm tending to **prohibit adding new content at all using overrides**. This is related to the issue you opened in https://github.com/cekit/cekit/issues/489.

Now, back to your original issue.

What you actually try to achieve here is what we call local development of modules. This is described here: http://docs.cekit.io/en/latest/guidelines/local-development.html#referencing-customized-modules. I would suggest creating a local module and using overrides to replace it. This may not be that convenient, but now you know why it is like it is and what are the options to (potentially) mitigate it.

Let's discuss it.

**Comment by errantepiphany** [comment]
I think I understand how modules are currently being processed, and the reasoning behind it. However, I believe env vars made available through overrides should be respected during module processing too (not just in the end image-to-Dockerfile translation). Here is my proposal for how I would like it to work:

**Module processing:**
1. Module env vars are added.
2. Overrides env vars are added, clobbering any pre-existing env vars.
3. Module is executed.

**Effective image:**
1. Module env vars are added.
2. Image env vars are added, clobbering any pre-existing env vars.
3. Overrides env vars are added, clobbering any pre-existing env vars.
4. Dockerfile is created.

Below please find an example of what this would mean:

### ORIGINAL FILES

**module.yaml** (animals)
```
name: animals
envs:
    - name: CAT
      value: mammal
    - name: WHALE
      value: fish
```

**module.yaml** (music)
```
name: music
envs:
    - name: BEETHOVEN
      value: classical
    - name: CURE
      value: metal
```

**image.yaml**
```
name: categorization
envs:
    - name: CROW
      value: bird
    - name: DOLLY
      value: country
```

**overrides.yaml**
```
envs:
    - name: WHALE
      value: mammal
    - name: CURE
      value: goth
    - name: CROW
      value: goth
```

### BUILD

**module processing** (animals)
```
name: animals
envs:
    - name: CAT (added by module)
      value: mammal
    - name: WHALE (added by module, overridden by overrides)
      value: mammal
    - name: CURE (added by overrides)
      value: goth
    - name: CROW (added by overrides)
      value: goth
```

**module processing** (music)
```
name: music
envs:
    - name: BEETHOVEN (added by module)
      value: classical
    - name: CURE (added by module, overridden by overrides)
      value: goth
    - name: WHALE (added by overrides)
      value: mammal
    - name: CROW (added by overrides)
      value: goth
```

**effective image**
```
name: categorization
envs:
    - name: CAT (added by module)
      value: mammal
    - name: WHALE (added by module, overridden by overrides)
      value: mammal
    - name: BEETHOVEN (added by module)
      value: classical
    - name: CURE (added by module, overridden by overrides)
      value: goth
    - name: CROW (added by image, overridden by overrides)
      value: goth
    - name: DOLLY (added by image)
      value: country
```

### CREATED

**Dockerfile**
```
ENV CAT=mammal
ENV WHALE=mammal
ENV BEETHOVEN=classical
ENV CURE=goth
ENV CROW=goth
ENV DOLLY=country
```

Thoughts/comments/concerns?

**Comment by spolti** [comment]
Sounds good to me, but the issue I got was that, if you have a env called A=B and override the env A to the value C, the final Dockerfile will have both variables. the behaviour is that CEKit is appending the envs instead overriding it.

**Comment by errantepiphany** [comment]
I would consider that a bug. If it doesn't exist, it should it. If it does exist, it should override it. (IMO)

**Comment by goldmann** [comment]
@spolti @errantepiphany  It's not that simple. You are adding an override to the image descriptor which does not have the env `A`, so it's added there and the value is `C`. This is how it works currently where you have modules defined. It's a bit unclear how it should be processed. Should it be added to all module descriptors? Or to just one? Which one? Should it be added to the image maybe? (like it is now) Should I maybe actually refrain from adding anything via overrides and make it possible to only change things? And so on...

**Comment by goldmann** [comment]
Generally speaking, I tend to move into direction where overrides *should not* be allowed to add new content. This would make all the things much easier.

**Comment by errantepiphany** [comment]
@goldmann I could be convinced to change my mind that overrides should not _add_ new content. However, I strongly feel that overrides should be able to _change_ existing content. In particular, **also during module processing**. That's the big issue we're facing.

**Comment by goldmann** [comment]
OK, let's try to structure the discussion a bit. My replies on the phone, while waling didn't help :)

What we are talking here about are two things:

1. How overrides should be applied to image descriptor and modules.
2. If overrides should allow for adding content (and not only changing things)

These two things sometimes are crossing paths, but generally we can think about them as separate things. Let's focus on the first problem.

With the refactoring done as part of 3.0 where module merging was rewritten, these are **not combined** internally at the build time. Instead, we rely on the Dockerfile format for our currently supported builder engines. This is **very important**. It means that we are not touching modules descriptors, we use them as these are defined, in the order presented in the image descriptor. This makes it very clear what is done when and what outcome could you expect.

If you look at the `target/image.yaml` file you will see that it does not contain anything related to modules. Again, this is different from CEKit 2.x.

Now, that we have this information, we can talk further.

Since we do not merge modules at all - **we do not apply overrides on module content/definition**.

With the current state of things, overrides can modify (add/change) image descriptor. Change are not propagated to modules.

If you want to modify a module, then you need to modify it (for example in a fork) and then use overrides to point your image descriptor to an updated version of the module. If you think about it - it actually makes sense. Modules are building blocks of your image, similarly to libraries. These are versioned, available at some location. If you are not happy with a module, then you need to propagate the change upstream, or as I mentioned above, fork it.

Although I understand that it would be handy to just override some module content, I would discourage such approach to minimize the complexity of the tool and to lower potential risk of changing something by accident that wasn't meant to be changed (in some other module).

Possibly the problem here is in the workflow you try to apply. Maybe this could be adjusted?

If you still think, that we should enable overrides in modules, let me ask a few questions:

1. How we will ensure that we do not modify content that is not supposed to be modified? Helper: two modules have same env var: `ABC`, but you want to modify only one of them, in the first module.
2. Should override be applied to all modules? If not, how you define to which module it should be applied?
3. Should the override be applied additionally to the **image descriptor** too?

**Comment by goldmann** [comment]
@luck3y @jmtd If you have any opinions on this, feel free to let us know!

**Comment by greenatatlassian** [comment]
Chiming in here since this same issue has now bitten us as well.

@goldmann and @errantepiphany both have some valid points though you are also approaching this from very different angles.

CEKit, perhaps by intentional design, perhaps by mistake/omission, doesn't allow an image descriptor to produce a `RUN` directive in the dockerfile. Effectively, image descriptors can only list things to _assembled_ into an image (modules, packages, files/artifacts). Image descriptors cannot directly enable _building_ an image, e.g. run some command, compile a file, etc. 

Overrides basically support DRY image configuration, as described in the opening paragraph of the docs on the subject. But if the only place you can _do_ (e.g. `RUN`) anything is in modules, then the power of overrides to make the descriptor tree DRY is limited to just deciding what parts to assemble, not how those parts are made.

In our use case, we need to build an upstream library from source, and produce a set of images each containing a different version of the library. The only thing changing between the image builds is the version of the upstream library. 

If I take @goldmann's approach, I should create a separate module for each version of the upstream library, though those modules will be identical except for the version number—possible, but not very clean or appealing.

If instead I follow @errantepiphany's suggestion for how things should work, then I simply parameterise the version in an env variable, and override it's value on the command line and my configuration remains DRY. 

I really appreciate that @goldmann is arguing for the encapsulation of modules—a great idea, though CEKit isn't really consistent on this, see e.g. #792, nor do I think there has been an effort to reach consensus on what it should be.

The question becomes "what is a module?" Should a module work in isolation, with no knowledge of anything around it? If so, then in the context of a container, the only way to really make this isolation complete is to have the module run in it's own build image, separate from the main/final image. If not, then we might as well embrace the fact that a module is running inside the image, affected by things that ran before it inside the same container, which seems to be the current design of CEKit.

Put differently, does CEKit enable both _building_ and _assembling_ images? (Where build means I need to e.g. compile code, while assemble means I just collect packages, external files, etc, without needing multi-stage builds or `RUN` directives). Currently, I think the code leans a bit more into _assembling_ and not so much into _building_. Modules do enable _building_, though ironically, the most important part of _building_ images is probably mult-stage dockerfiles, which are only supported at the image level. 

Much of the discussion really comes down to ordering, something that has also come up in #790, #792, and probably needs it's own discussion to reach some clarity.

For this particular issue I would propose the following solution, though this should be tempered by any general discussion on ordering:
 1. things like `from`, `envs` that translate into dockerfile directives that affect subsequent steps should be taken from the image descriptor. We should decide what is included here carefully, and make sure it is well documented.
 2. Overrides from the commandline should be applied to these directives.
 3. These can then be put at the top of the docker file.
 4. Module processing goes next. Command line overrides are not applied to modules. Modules can define their own `envs` for things they don't want overridden. Otherwise, they will inherit the env of the previous dockerfile content/modules (as they already do currently).
 5. Once module processing is complete, `envs` from the image descriptor (with overrides) are again written into the dockerfile, so the final image has the values from the image descriptor `envs`.

The only other options I really see here are:
- Admit that some overrides, such as `envs`, are actually so limited in scope as to be useless and remove them from the list of things that can be overridden.
- Allow overriding specific module values with some additional syntax/structure to the override descriptor.

Given the current state of things, we probably will consider using a template image and modules, and then write those out for each version before running CEKit as a work around for our particular use case.

**Comment by greenatatlassian** [comment]
A teammate pointed out that for our use case, we could take @goldmann's approach, but rather than duplicating the whole library build module for each version, we could instead extract the environment variables into their own module that runs before the library build. So the library build is not duplicated, but uses environment variables (parameters) from the small library environment module, which there is one of for each library version we need to support.

Specifically:


Given modules:
```yaml
name: library-install
version: "1.0"

execute:
  # Note script requires LIB_VERSION to be defined
  - script: install-library.sh
    user: root
```

```yaml
name: library-env
version: &version "3.4"

envs:
  - name: LIB_VERSION
    value: *version
```

```yaml
name: library-env
version: &version "3.6"

envs:
  - name: LIB_VERSION
    value: *version
```

We can then have an image:
```yaml
name: image-with-library

modules:
  install:
    - name: library-env
      version: 1.0
    - name: library-install
```

and call cekit like so:
```
# build image with library version 3.4:
cekit build --overrides '{"modules": {"install": [{"name": "library-env", "value": "3.4"}]}}' docker
# build image with library version 3.6:
cekit build --overrides '{"modules": {"install": [{"name": "library-env", "value": "3.6"}]}}' docker
```

Hopefully that is a useful approach to others.
