### ISSUE TITLE
Disabling content sets using YAML null values is not possible

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#533]
**Describe the solution you'd like**
The yaml's remove character is not accepted by CEKit thus not possible to remove a property from the image.yaml using overrides file.

Example: given the following image.yaml file: 

```yaml
schema_version: 1

name: "image-name"
version: "1.1"
from: "ubi8"
labels:
  - name: "com.redhat.component"
    value: "image"
packages:
  content_sets_file: content_sets.yml
  install:
    - java-1.8.0-openjdk-headless
```

And supposing we want the remove the content_sets_file property using an overrides file:

```yaml
schema_version: 1

name: "rhpam-7/rhpam7-dev-apb"
from: "ansibleplaybookbundle/apb-base:v3.11"

packages:
  content_sets_file: ~
```

It will fail with the following message:

```
TypeError: join() argument must be str or bytes, not 'NoneType'
```

using `null` produces the same result.
