### ISSUE TITLE
Variable expansion in modules

### ISSUE THREAD

**Issue by cescoffier** [cekit/cekit#558]
**Describe the solution you'd like**
It may be already supported but I was unable to find it in the doc (so let me know if it's an existing feature).

I have a module with new versions very regularly. Something like this:

```
#...
version: "19.1.0"

envs:
# ...
  - name: "GRAALVM_VERSION"
    value: "19.1.0"

artifacts:
- name: graalvm-ce-linux-amd64-19.1.0.tar.gz
  url: https://github.com/oracle/graal/releases/download/vm-19.1.0/graalvm-ce-linux-amd64-19.1.0.tar.gz
  md5: c6900b26b60d3bd3d0274480a56d6845
 # ...
```

To avoid to repeat the version everywhere (in the file name, the url, the env...) I was wondering if I could use variable expansion so I could write something like:

```
- name: graalvm-ce-linux-amd64-${GRAALVM_VERSION}.tar.gz
```
