### ISSUE TITLE
Multi-stage overrides are only applied to the last image definition

### ISSUE THREAD

**Issue by ryanemerson** [cekit/cekit#648]
**Describe the bug**
Overrides supplied via the cli are only applied the last image defined in a multi-stage build. It should be possible for overrides to be applied to any of the defined images.

**To reproduce**
```yaml
- name: builder
  version: 1.0
  from: registry.access.redhat.com/ubi8/ubi-minimal:8.2-267

- name: runner
  version: 1.0
  from: registry.access.redhat.com/ubi8/ubi-minimal:8.2-267

```

`cekit build --overrides '{"version": "SNAPSHOT"}' podman`

Overriding the version in this fashion is not necessarily useful, it is just a simple example of the problem.

**Expected behavior**
It should be possible to override nodes on any of the defined images in the descriptor.

**Environment information:**
 - Operating system: Fedora 30
 - CEKit version: 3.6.0
