### ISSUE TITLE
Allow extra build instructions for Dockerfile

### ISSUE THREAD

**Issue by tchughesiv** [cekit/cekit#684]
**Describe the solution you'd like**
CEKit is limited in its current state when it comes to image build instructions. We need a way to add additional instructions to a resulting Dockerfile, specifically COPY... apart from what’s already done w/ artifacts. I propose the following:
```
extra_instructions:
  copy:
    - src: ‘manifests/’
      dst: ‘/manifests’
    - src: ‘metadata/’
      dst: ‘/metadata’
```

This is not limited to COPY though, other instructions that CEKit doesn't currently support could also be included here... for example:
```
extra_instructions:
   stopsignal: <str>
   arg:
    - key: <str>
      value: <str>
   copy:
    - src: <str>
      dst: <str>
```

**Additional context**
An example of this would be for operator bundle builds in osbs when using `osbs.extra_dir`. Without using lookaside cache/artifacts, we need to add the contents of that extra directory via the following Dockerfile lines.
```
       COPY \
            manifests/ \
            /manifests
       COPY \
            metadata/ \
            /metadata
```

This is not possible today and is required because osbs digest pinning does not allow the use of lookaside cache. An error is thrown when lookaside cache is detected and the build fails.
