### ISSUE TITLE
Clarify the rpm option to install enable extra yum repositories

### ISSUE THREAD

**Issue by spolti** [cekit/cekit#707]
**Describe the solution you'd like**

CEKit image descriptor allows you to use the following configuration to add extra repositories:
```
packages:
  repositories:
    - name: epel
      rpm: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  install:
    - jq
```

It works fine with yum and dnf, but for images that just include the `microdnf` this does not work as expected.

However, the docs don't make it clear that the repository manager needs to support install a new repo from a URL.
```
dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```

Microdnf does not have this ability, instead, it will try to install the provided URL as a package, leading the image build to fail.

To work around this, the best option is to use a module and use `rpm -i` to enable the new repo.

Would be a good addition to the CEKit docs to clarify the exact usage of the `rpm` key to avoid such misusage like this. :)

**Additional context**
Add any other context about the feature request here.
