### ISSUE TITLE
OSBS support for gating.yaml and help.md files

### ISSUE THREAD

**Issue by kyguy** [cekit/cekit#737]
**Describe the solution you'd like**
OSBS requires special files in the root directory of dist-git directories in order to preform builds. Cekit offers integration to copy/generate some of these files (e.g. content_sets.yml, container.yaml) but not all required files (e.g gating.yaml, help.md). We need some way of generating/coping the following files into the root directory of our dist-git repos
- gating.yaml
- help.md

In the past we used `extra_dir` field [1] to copy these files to the root directory of our dist-git repos however, this behaviour of `extra_dir` changed with Cekit 3.11.0 [2] making it impossible to copy files to the root directory of dist-git repos. 

We could solve this in a couple ways:

Making `help` and `gating` fields like the `container` field in the `osbs.configuration` section, allowing users to specify the text for these files. Cekit would then generate files based on this text and copy the files to dist-git
```
# Embedding
osbs:
    configuration:
        # Configuration is embedded directly in the container key below
        container:
            compose:
                pulp_repos: true
        help: -|
            < help.md text here >
        gating: -|
            < gating.yaml text here >
```

Alternatively, we could extend `extra_dir` field so that Cekit can copy the contents of the `extra_dir` to the root of a dist-git repo when the `/*` suffix is provided, e.g.
```
osbs:
    extra_dir: osbs-extra/*
    extra_dir_target: /
```
would cause the contents of `extra_dir`instead of `extra_dir` itself to be copied to the root directory of a dist-git repo, 

[1] https://github.com/cekit/cekit/pull/519
[2] https://github.com/cekit/cekit/pull/709
