### ISSUE TITLE
artifact handling: md5 sums special-cased, other sum types not supported for cache copy

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#741]
Say you have an artifact definition as follows

```
artifacts:
- name:   java-17-openjdk-headless-17
  target: java-17-openjdk-headless-17.0.0.0.26-0.1.ea.el8.x86_64.rpm
  sha256: 2751509558cef22e3c69aae4414521946a7fff2c0b35c4e225895dea2bf52ea7
```

Cekit (3.11.0) will fail the build with

    ERROR Resource '{'name': 'java-17-openjdk-headless-17', 'target': 'java-17-openjdk-headless-17.0.0.0.26-0.1.ea.el8.x86_64.rpm', 'sha256': '2751509558cef22e3c69aae4414521946a7fff2c0b35c4e225895dea2bf52ea7'}' is not supported

The issue is that when none of 'image','path','url' or 'git' keys are specified, `create_resource` has [one more logic check for the `md5` key](https://github.com/cekit/cekit/blob/ca7384c7f8f902c2994a684dd0241a2fde52094d/cekit/descriptor/resource.py#L55) before failing with the above message.

1. that branch should be updated to check for any of the supported hash types
2. the error message should be rewritten to be clearer as to what the problem is

The work-around in my case is to add `md5` keys.

**Comment by rnc** [comment]
Actually technically PlainResource (currently) _requires_ md5 and other hashes are optional. Investigating...

**Comment by rnc** [comment]
Apparently Brew/Koji does support md5/sha1 and sha256 **but** all of the CEKit to download an artifact is targeted at **maven** artifacts - I do think the documentation needs a note here.

**Comment by jmtd** [comment]
Yeah, I discovered sadly that the brew artifact support was maven artifacts only atm. What I've done [here](https://github.com/jmtd/openjdk/blob/jdk17-epel-test/modules/jdk/17/module.yaml#L36) as a temporary first measure requires cekit to commit the artifacts to dist-git which is obviously far from ideal. (This is just until we've got the proper brew targets/buildroots/etc set up internally)

**Comment by rnc** [comment]
Unfortunately https://osbs.readthedocs.io/en/latest/users.html#fetch-artifacts-koji-yaml also only supports Maven type artifacts. The brute-force method of https://osbs.readthedocs.io/en/latest/users.html#fetch-artifacts-url-yaml would work but then we're exposing internal URLs. 
Aren't those RPMs in a repo you could access to avoid this?

**Comment by rnc** [comment]
I'm keeping this open for the PR for commit https://github.com/rnc/cekit/commit/01290c74041cb3a2e8e93ccc76033c803275c85b

**Comment by jmtd** [comment]
I wasn't relying on brew lookaside-cache, but on the cekit behaviour of explicitly copying stuff from the local cekit cache directly into the dist-git repo, and committing it there. It's that behaviour which only works with `md5` keys, although there's no obvious reason it couldn't with the other types.

>  Aren't those RPMs in a repo you could access to avoid this?

No, not yet; but they are in Brew, so I can pull them in with a particular compose:

```
compose:
  packages:
  - java-17-openjdk
  - java-17-openjdk-devel
  - java-17-openjdk-headless
  pulp_repos: true
  signing_intent: unsigned
```

We also needed to set up the Brew targets and tags and tag the latest internal builds of those above packages into the relevant buildroot tag. It took a while to get that all set up, so my hacky artifact-based builds were just to get something done before that was in place, and I don't need them anymore.
