### ISSUE TITLE
Docker file ordering prevents modules from using installed packages in their execute scripts.

### ISSUE THREAD

**Issue by greenatatlassian** [cekit/cekit#790]
**Describe the bug**
I have a module that will be installed in an image. That module includes an `execute` script that makes use of some packages that should be installed in the image (e.g. fortune). In my image descriptor, I include those packages to be installed, and the module. However, docker build fails because the package required by the execute script is not installed in the image.

**To reproduce**
Image descriptor:
```yaml
from: alpine:latest
modules:
  install:
  - name: test_module
  repositories:
  - name: modules
    path: modules/
name: test_image
packages:
  install:
  - fortune
  manager: apk
version: '1.0'
```
Module descriptor:
```yaml
name: test_module
version: 1.0
install:
  - script: run_fortune.sh
```
`run_fortune.sh` install script:
```bash
#!/bin/bash
fortune
```

**Expected behavior**
I would expect that packages listed in the `packages` section of the image descriptor would be installed *before* any *execute* steps from modules are run.
