### ISSUE TITLE
Installation of any package with a specific version through `apt-get` in the CEKit modules fails

### ISSUE THREAD

**Issue by ankithbtik** [cekit/cekit#813]
**Describe the bug**
Installation of any package with a specific version through `apt-get` in the CEKit modules fails.

**To reproduce**

1. Create a module (`module.yaml`)
2. Edit that module and add `packages` -> `install` section
3. Use the package manager `apt-get`
4. List any package for installation but with a specific version, for ex. `java-17-amazon-corretto-jdk=1:17.0.4.9-1`
5. My complete `module.yaml` looks like,
```
schema_version: 1

name: install.jdk
version: 1.0
description: "Installs the mentioned version of Java-17 JDK"

packages:
  manager: apt-get
  install:
    - java-17-amazon-corretto-jdk=1:17.0.4.9-1
```

**Expected behavior**
CEKit should be able to build a docker image in which `java-17-amazon-corretto-jdk`  with version `1:17.0.4.9-1` is installed.

**Logs**
```
cekit --version
4.3.0
```

```
cekit build docker

[error] dpkg-query --list java-17-amazon-corretto-jdk=1:17.0.4.9-1' returned a non-zero code: 1
```

**Environment information:**
 - Operating system : macos, linux
 - CEKit version: 4.3.0

**Additional context**
The issue occurs in the step where CEKit adds an additional command for listing the installed packages (i.e. `dpkg-query`) after each installation. See [line #139](https://github.com/cekit/cekit/blob/develop/cekit/template_helper.py#L139). If the package is listed with a specific version (for ex. `xyz=1.0.0`) in the `module.yaml` then `dpkg-query` is trying to find the package along with the version, which it doesn't find and throws an error. The simple fix is to strip the version before giving the input to `dpkg-query`. The fix will go here at [line #46](https://github.com/cekit/cekit/blob/develop/cekit/templates/template.jinja#L46).
