### ISSUE TITLE
Support for `microdnf reinstall` command?

### ISSUE THREAD

**Issue by ppatierno** [cekit/cekit#843]
Hi all,
we would need to reinstall a package by using microdnf, so having the cekit generating a Dockerfile having something like:

```shell
microdnf reinstall ...
```

We use something like 

```yaml
packages:
  manager: microdnf
  install:
    - <package>
    - <package>
```

to get a `microdnf install` command.

Looking at the documentation https://docs.cekit.io/en/latest/descriptor/image.html#packages-to-install I don't see a way to do have a `reinstall` command.
Is there some option I am missing? Any workaround to this?

**Comment by jmtd** [comment]
Workaround would be to call it from a shell script that you get copied into the image using `execute: script: foo.sh` instruction. Take a look at e.g. https://github.com/jboss-container-images/openjdk/blob/ubi9/modules/util/pkg-update/module.yaml and https://github.com/jboss-container-images/openjdk/blob/ubi9/modules/util/pkg-update/execute.sh

**Comment by ppatierno** [comment]
That seems to be a good suggestion. We actually already have script in a module to run. We could add the command there. Thanks. I will let you know if it works for us ;-)

**Comment by rnc** [comment]
I wonder if it would be useful to have a `packages to remove` option in https://docs.cekit.io/en/latest/descriptor/image.html#packages - and then the timezone package could be installed again after removal. This might solve it in a more generic way.
@goldmann thoughts?

**Comment by kyguy** [comment]
Having a `reinstall` field like the `install` filed would be pretty cool, something like 
```
packages:
  manager: microdnf
  install:
    - java-11-openjdk-devel
  reinstall:
    - tzdata
```
