### ISSUE TITLE
Add phase to install files into the container

### ISSUE THREAD

**Issue by jmtd** [cekit/cekit#931]
**Describe the solution you'd like**

I'd like a clear, declarative way of installing files from a module into the container image, with specific permissions and suchlike. E.g. (this to be refined)

```
install:
- src: artifacts/run-java.sh
  dst: /opt/jboss/container/java/run/run-java.sh
  mod: 0755
  owner: root
  group: root
```

**Additional context**

It's very common to have a pattern like this at the moment

```
execute:
- script: configure.sh
```

Where the configure script is basically doing 

```
#!/bin/sh
# Configure module
set -e

SCRIPT_DIR=$(dirname $0)
ARTIFACTS_DIR=${SCRIPT_DIR}/artifacts

chown -R $USER:root $SCRIPT_DIR
chmod -R ug+rw,+X $SCRIPT_DIR
chmod +x ${ARTIFACTS_DIR}/opt/jboss/container/java/run/*

pushd ${ARTIFACTS_DIR}
cp -pr * /
popd
```

or variations thereof.

It would be both a space and time-saver, as well as aid in auditing and keeping things consistent, to manage this with a cekit phase.

Add any other context about the feature request here.
